package io.confluent.developer.k8s

import io.fabric8.kubernetes.api.model.apps.DeploymentBuilder
import io.fabric8.kubernetes.client.Config
import io.fabric8.kubernetes.client.DefaultKubernetesClient

fun main() {
  val config = Config.autoConfigure(null)
  val client = DefaultKubernetesClient(config).inNamespace("default")

  val appName = "streaming-movie-ratings"
  val defaultLabels = mapOf("app" to appName)

  val deployment = DeploymentBuilder()
      .withNewMetadata()
        .withName(appName)
        .withNamespace("default")
        .withLabels(defaultLabels)
      .endMetadata()
      .withNewSpec()
        .withReplicas(1)
        .withNewSelector()
          .withMatchLabels(defaultLabels)
        .endSelector()
        .withNewTemplate()
          .withNewMetadata()
            .withLabels(defaultLabels)
          .endMetadata()
          .withNewSpec()
            .addNewImagePullSecret()
              .withName("regcred")
            .endImagePullSecret()
            .withNewAffinity()
              .withNewPodAffinity()
                .addNewRequiredDuringSchedulingIgnoredDuringExecution()
                  .withTopologyKey("kubernetes.io/hostname")
                  .withNewLabelSelector()
                    .addNewMatchExpression()
                      .withKey("app")
                      .withOperator("In")
                      .withValues(appName)
                    .endMatchExpression()
                  .endLabelSelector()
                .endRequiredDuringSchedulingIgnoredDuringExecution()
              .endPodAffinity()
            .endAffinity()
            .addNewContainer()
              .withName(appName)
              .withImage("gamov-docker.jfrog.io/dev/streaming-movie-ratings:latest")
              .addNewVolumeMount()
                .withName("config")
                .withMountPath("/var/config")
                .withReadOnly(true)
              .endVolumeMount()
              .addNewEnv()
                .withName("JAVA_TOOL_OPTIONS")
                .withValue("-DLOGLEVEL=INFO")
              .endEnv()
            .endContainer()
            .addNewVolume()
              .withName("config")
              .withNewSecret()
                .withSecretName("ccloud")
                .addNewItem()
                  .withKey("config")
                  .withPath("config.ccloud")
                .endItem()
              .endSecret()
            .endVolume()
          .endSpec()
        .endTemplate()
      .endSpec()
      .build()

  client.apps().deployments().createOrReplace(deployment)
}
