{
 "title": "Kafka Connect",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kafka Connect Dead Letter Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "DLQ requests diff - $tag_typeName",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "typeName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "task-error-metrics",
     "select": [
      [
       {
        "params": [
         "deadletterqueue-produce-requests"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "DLQ Failures total - $tag_typeName",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "typeName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "task-error-metrics",
     "select": [
      [
       {
        "params": [
         "deadletterqueue-produce-failures"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DLQ requests total - $tag_typeName",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "typeName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "task-error-metrics",
     "select": [
      [
       {
        "params": [
         "deadletterqueue-produce-requests"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connector Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "connector-count",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "connect-worker-metrics",
     "select": [
      [
       { "params": [ "connector-count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kafka Connect Consumer Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "$tag_typeName",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "typeName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kafka-consumer-metrics",
     "select": [
      [
       { "params": [ "request-rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kafka Connect Consumer Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "$tag_typeName reads",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "typeName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sink-task-metrics",
     "select": [
      [
       { "params": [ "sink-record-read-rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_typeName sends",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "typeName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sink-task-metrics",
     "select": [
      [
       { "params": [ "sink-record-send-rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kafka Connect Error Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_typeName",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "typeName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "task-error-metrics",
     "select": [
      [
       { "params": [ "total-record-errors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  }
 ]
}