{
 "title": "Kafka Connect - by Connector",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Connector",
    "query": "show tag values with key =\"typeName\" where \"typeName\"=~/connector/"
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka Connect Sink - Read message totals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Total" }
   ],
   "targets": [
    {
     "alias": "read",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "typeName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sink-task-metrics",
     "query": "SELECT mean(\"sink-record-read-total\") FROM \"sink-task-metrics\" WHERE (\"typeName\" =~ /$Connector/) AND $timeFilter GROUP BY time(5s), \"typeName\" fill(null)",
     "select": [
      [
       { "params": [ "sink-record-read-total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "typeName", "operator": "=~", "value": "/^$Connector$/" }
     ]
    },
    {
     "alias": "send",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "typeName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sink-task-metrics",
     "query": "SELECT mean(\"sink-record-send-total\") FROM \"sink-task-metrics\" WHERE (\"typeName\" =~ /$Connector/) AND $timeFilter GROUP BY time(5s), \"typeName\" fill(null)",
     "select": [
      [
       { "params": [ "sink-record-send-total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "typeName", "operator": "=~", "value": "/^$Connector$/" }
     ]
    }
   ]
  },
  {
   "title": "Kafka Connect - Send/Error totals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "total record errors",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "typeName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "task-error-metrics",
     "query": "SELECT mean(\"total-record-errors\") FROM \"task-error-metrics\" WHERE (\"typeName\" =~ /$Connector/) AND $timeFilter GROUP BY time(5s), \"typeName\" fill(null)",
     "select": [
      [
       { "params": [ "total-record-errors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "typeName", "operator": "=~", "value": "/^$Connector$/" }
     ]
    },
    {
     "alias": "total records sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sink-record-send-total\") FROM \"sink-task-metrics\" WHERE (\"typeName\" =~ /$Connector/) AND $timeFilter GROUP BY time(5s), \"typeName\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kafka Connect Dead Letter Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "DLQ produce requests total",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "typeName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "task-error-metrics",
     "query": "SELECT mean(\"deadletterqueue-produce-requests\") FROM \"task-error-metrics\" WHERE (\"typeName\" =~ /$Connector/) AND $timeFilter GROUP BY time(5s), \"typeName\" fill(null)",
     "select": [
      [
       {
        "params": [
         "deadletterqueue-produce-requests"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "typeName", "operator": "=~", "value": "/^$Connector$/" }
     ]
    }
   ]
  }
 ]
}