apiVersion: v1
kind: Secret
metadata:
  name: spring-boot-application-properties
type: Opaque
stringData:
  application.properties: |
    spring.kafka.properties.sasl.mechanism=PLAIN
    spring.kafka.properties.bootstrap.servers=
    spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule   required username=''   password='';
    spring.kafka.properties.security.protocol=SASL_SSL
    # Kafka Producer | KafkaTemplate
    spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.IntegerSerializer
    spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
    spring.kafka.streams.replication-factor=3
    spring.application.name=orders-matview




  
  