= Pre-requisites
:doctype: book

* Docker version 17.06.1-ce
* Docker Compose version 1.14.0 with Docker Compose file format 2.1
* https://docs.confluent.io/current/cloud-quickstart.html#step-2-install-ccloud-cli[Confluent Cloud CLI]
* https://confluent.cloud[An initialized Confluent Cloud cluster used for development only]

= Setup

NOTE: Use this in a _non-production_ Confluent Cloud instance for development purposes only.

On the host from which you are running Docker, ensure that you have properly initialized Confluent Cloud CLI and have a valid configuration file at `$HOME/.ccloud/config`.

Step 1: Generate a file of ENV variables used by Docker to set the bootstrap servers and security configuration

[source,bash]
----
$ ./ccloud-generate-env-vars.sh
----

Step 2: Source that file of ENV variables

[source,bash]
----
$ source ./delta_configs/env.delta
----

= Bring up services

Make sure you completed the steps in the Setup section above before proceeding.

You may bring up all services in the Docker Compose file at once or individually.

== All services at once

[source,bash]
----
$ docker-compose up -d
----

== Confluent Schema Registry

[source,bash]
----
$ docker-compose up -d schema-registry
----

== Kafka Connect

[source,bash]
----
$ docker-compose up -d connect
----

== Confluent Control Center

[source,bash]
----
$ docker-compose up -d control-center
----

== KSQL Server

[source,bash]
----
$ docker-compose up -d ksql-server
----

== KSQL CLI

[source,bash]
----
$ docker-compose up -d ksql-cli
----

== Confluent REST Proxy

[source,bash]
----
$ docker-compose up -d rest-proxy
----
