= Building a Streaming Data Pipeline with Kafka Streams and KSQL
Ricardo Ferreira<ricardo@confluent.io>, Viktor Gamov <viktor@confluent.io>, © 2019 Confluent, Inc.
:toc: auto
:toc-placement: auto
:toc-position: right
:toc-title: Table of content
:icons: font
:source-highlighter: highlight.js
:highlightjs-theme: idea
:experimental:

== Prerequisites

Welcome to the https://www.jfokus.se/jfokus19/talks/2585[«Building a Streaming Data Pipeline with Kafka Streams and KSQL»] workshop.

To be successful in executing all exercises, you need to have following installed.

* Docker CE Version 18.09.1
+
NOTE: It is OK to use Windows, but the trainers are not Windows users and may not be able to help with Windows related issues.
* Git
* JDK (min JDK 8)
** Recommended way
*** Install https://sdkman.io/install[sdkman]
*** `sdk list java`
*** `sdk install java <verison-provider>` e.g. `sdk install java 8.0.201-zulu`
* https://www.jetbrains.com/idea/download/[IntelliJ IDEA Community Edition]
* https://docs.docker.com/install/[Docker CE]
* Docker Compose Version 1.20.0 | with Docker Compose file format 2.1
* https://docs.confluent.io/current/cloud-quickstart.html#step-2-install-ccloud-cli[Confluent Cloud CLI]
* https://confluent.cloud[An initialized Confluent Cloud Cluster used for Development Only]
** We will perform this exercise in the class

== Creating Topics and Validating Data Flowing

=== Creating Raw Data Topics

[source,bash]
----
$ ccloud topic create raw-movies --partitions 16 --replication-factor 3
$ ccloud topic create raw-ratings --partitions 16 --replication-factor 3
----

=== Producing and Consuming Data using Confluent Cloud CLI

Open a terminal to consume records from the `raw-movies` topic using the following command:

[source,bash]
----
$ ccloud consume -t raw-movies
----

Open another terminal to produce records to the `raw-movies` topic using the following command:

[source,bash]
----
$ cat ../data/movies.dat | ccloud produce -t raw-movies
----

Open another terminal to consume records from the `raw-ratings` topic using the following command:

[source,bash]
----
$ ccloud consume -t raw-ratings
----

Open another terminal to produce records to the `raw-ratings` topic using the following command:

[source,bash]
----
$ cat ../data/ratings.dat | ccloud produce -t raw-ratings
----

=== Creating Workshop Related Topics

[source,bash]
----
$ sh create-demo-topics.sh
----

You should see the following output:

[source,bash]
----
Topic "movies" created.
Topic "rating-sums" created.
Topic "rating-counts" created.
Topic "average-ratings" created.
Topic "rated-movies" created.
----

== Connecting Docker with Confluent Cloud Cluster

NOTE: Use this in a _non-production_ Confluent Cloud instance for development purposes only.

On the host from which you are running Docker, ensure that you have correctly initialized Confluent Cloud CLI and have a valid configuration file at `$HOME/.ccloud/config`. More information https://docs.confluent.io/current/cloud/cli/install.html[here].

=== Step 1: Generate a file that exports environment variables used by Docker to set up the bootstrap servers and authentication details.

[source,bash]
----
$ ./ccloud-generate-env-vars.sh
----

=== Step 2: Source the generated file to make the exports available in the current path.

[source,bash]
----
$ source ./delta_configs/env.delta
----


== Bring up Services from Confluent Platform

Make sure you completed the steps in the Setup section above before proceeding.
You may bring up all services in the Docker Compose file at once...

=== All Services At-Once

[source,bash]
----
$ docker-compose up -d
----

=== ...or individually...

==== Confluent Schema Registry

[source,bash]
----
$ docker-compose up -d schema-registry
----

==== KSQL Server

[source,bash]
----
$ docker-compose up -d ksql-server
----

==== KSQL CLI

[source,bash]
----
$ docker-compose up -d ksql-cli
----

==== Confluent Control Center

[source,bash]
----
$ docker-compose up -d control-center
----

== Validate If KSQL Server And CLI Is Working Properly

Before moving forward with this workshop you need to validate if KSQL is working as expected.
Thus, bring up the KSQL CLI using the command below:

[source,bash]
----
$ docker run --network workshop_default --rm --interactive --tty confluentinc/cp-ksql-cli:5.1.0 http://ksql-server:8088
----

You should be presented with a prompt as shown below:

[source,bash]
----

                  ===========================================
                  =        _  __ _____  ____  _             =
                  =       | |/ // ____|/ __ \| |            =
                  =       | ' /| (___ | |  | | |            =
                  =       |  <  \___ \| |  | | |            =
                  =       | . \ ____) | |__| | |____        =
                  =       |_|\_\_____/ \___\_\______|       =
                  =                                         =
                  =  Streaming SQL Engine for Apache Kafka® =
                  ===========================================

Copyright 2017-2018 Confluent Inc.

CLI v5.1.0, Server v5.1.0 located at http://ksql-server:8088

Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!

ksql>
----

This means that the KSQL CLI was able to connect the KSQL Server and therefore, able to present a working prompt.
In the KSQL CLI prompt, enter the following command:

[source,bash]
----
PRINT 'raw-movies' FROM BEGINNING;
----

You should see all the records that you loaded into the topic `raw-movies` previously.
Press kbd:[Ctrl + C] to interrupt the print command and go back to the KSQL CLI prompt, and thereafter type `exit` then `ENTER` to exit the prompt and finish the KSQL CLI session.
