SET 'auto.offset.reset' = 'earliest';

CREATE STREAM SYSLOG (HOST VARCHAR) WITH (KAFKA_TOPIC='syslog_dummy', VALUE_FORMAT='JSON');

CREATE STREAM PRODUCTS (SKU VARCHAR, PRODUCT VARCHAR) WITH (KAFKA_TOPIC='products', VALUE_FORMAT='JSON');

CREATE STREAM ORDERS (ORDER_ID INT, CUSTOMER_ID INT, ORDER_TS VARCHAR, ORDER_TOTAL_USD DOUBLE) WITH (KAFKA_TOPIC='orders', VALUE_FORMAT='JSON');

CREATE STREAM CUSTOMERS (ID INT, FIRST_NAME VARCHAR, LAST_NAME VARCHAR, EMAIL VARCHAR, COUNTRY VARCHAR) WITH (KAFKA_TOPIC='customers', VALUE_FORMAT='JSON');

CREATE STREAM UBNT_USERS (DEVICE_TYPE VARCHAR, DEVICE_NAME VARCHAR) WITH (KAFKA_TOPIC='ubnt_users', VALUE_FORMAT='JSON');

CREATE STREAM STORE_CUSTOMERS (STORE_ID VARCHAR, NAME VARCHAR, EMAIL VARCHAR, DO_NOT_CONTACT_EMAIL INT, ACTIVE INT) WITH (KAFKA_TOPIC='store_customers',VALUE_FORMAT='JSON');

CREATE STREAM PAGEVIEWS WITH (KAFKA_TOPIC='pageviews',VALUE_FORMAT='AVRO');

SELECT * FROM SYSLOG LIMIT 1;
SELECT * FROM PRODUCTS LIMIT 1;
SELECT * FROM ORDERS LIMIT 1;
SELECT * FROM CUSTOMERS LIMIT 1;
SELECT * FROM UBNT_USERS LIMIT 1;
SELECT * FROM STORE_CUSTOMERS LIMIT 1;
